### ISSUE TITLE
Estudo das funções

### ISSUE THREAD

**Issue by CorreiaJV** [fga-eps-mds/Tema03-timeb#1]
# Descrição
Estudar qual a sua função e quais os papéis deverão ser desempenhados durante a disciplina 

# Tarefas 
- [x] Estudar o que é um Scrum Master
 - [x]  Estudar o que é um Product Owner(PO)
 - [x]  Estudar o que é um DevOps
 - [x]  Estudar o que é um Arquiteto de Software 
 - [x]  Estudar o que é um desenvolvedor

# Critérios de Aceitação 
- [x] Compartilhar aprendizado com o grupo

**Comment by MtsSrs** [comment]
DevOps: atua ao mesmo tempo nas áreas de desenvolvimento de sistemas e infraestrutura de operações, sendo responsável por otimizar a produtividade (desenvolvimento) e a confiabilidade (infraestrutura), para que o resultado final atenda todas as necessidades dos clientes.
[Bibliografia](https://www.digitalhouse.com/br/blog/devops)

**Comment by MateusCaltabiano** [comment]
Scrum Master: 

O Scrum Master é o líder da equipe Scrum, sendo o responsável por defender o projeto, fornecendo orientação à equipe e ao proprietário do negócio para garantir que todas as práticas sejam seguidas. Além de abordar as facetas do processo de desenvolvimento ágil, o Scrum Master facilita a comunicação e a colaboração entre todos os envolvidos no projeto. As responsabilidades do Scrum Master variam conforme as necessidades da empresa e de seu time. Para projetos que usam metodologias ágeis, um Scrum Master é fundamental. Ele desempenha o papel de facilitador e coach para equipes de desenvolvimento ágil, garantindo que os produtos sejam entregues dentro do prazo e com a qualidade especificada.

**Comment by iagocabral** [comment]
## Papel do desenvolvedor

Um software, em sua estrutura básica, é composto por uma série de códigos interligados e relacionados que formam um produto virtual. O papel do desenvolvedor é criar sequências de códigos que, quando executados, consigam dar vida a uma aplicação de diversos tipos. Para isso, são usadas as linguagens de programação, como python, java, ruby e muitas outras.
[Bibliografia](https://blog.unyleya.edu.br/sem-categoria/desenvolvimento-de-software/)

**Comment by CorreiaJV** [comment]
# Papel do Arquiteto de Software
De uma maneira simplificada, podemos dizer que um arquiteto de software é o responsável por mapear o funcionamento do sistema. É quem identifica possíveis problemas e apresenta soluções efetivas.
O arquiteto tem como foco garantir a conformidade dos processos, das documentações e guias, direcionando a equipe nas atividades. Por isso, deve ter um bom entendimento das múltiplas plataformas e linguagens.
[Bibliografia](https://posdigital.pucpr.br/blog/o-que-faz-um-arquiteto-de-software)

**Comment by phnog** [comment]
O Product Owner (P.O., Dono do Produto) é o membro do Scrum Teamresponsável por direcionar o projeto de acordo com a necessidade do cliente e das demais partes interessadas. Ele é a única pessoa responsável por definir o produto, incrementado-o de acordo com o andamento do projeto.

Em um Time de Scrum, há apenas um Product Owner, que toma as decisões concernentes ao produto. Isso acontece para que não haja divergência na definição do produto, o que prejudicaria o bom andamento do projeto.

A função do Product Owner é tomar as decisões visando maximizar o trabalho de todos os envolvidos visando obter o retorno mais alto possível para o cliente.

[Bibliografia](https://www.voitto.com.br/blog/artigo/product-owner)
