### ISSUE TITLE
Pesquisa de tecnologias a serem utilizadas no projeto 

### ISSUE THREAD

**Issue by MateusCaltabiano** [fga-eps-mds/Tema03-timeb#12]
# Descrição
Pesquisar sobre como as diferentes tecnologias influenciariam nosso projeto e escolher quais utilizaremos.
# Tarefas

- [x] Pesquisar diferentes tecnologias
- [x] Brainstorm de pontos fortes e fracos
- [x] Definir as tecnologias que melhor se encaixam no projeto
# Critérios de aceitação
- [x] Compartilhar pesquisa e brainstorm com o grupo

**Comment by CorreiaJV** [comment]
Link do Brainstorm: [Brainstorm tecnologias](https://miro.com/app/board/uXjVOR-PCXE=/?invite_link_id=348997643090)
