### ISSUE TITLE
Treinamento de Git/Github

### ISSUE THREAD

**Issue by Julio-eng** [fga-eps-mds/Tema03-timeb#16]
# Descrição
Capacitação dos membros do time em Git e Github.
# Tarefa
- [x] Estudo dos comandos básicos do Git
- [x] Aprender as funcionalidades do Git/Github
- [x] Comentar na issue após fazer o treinamento

# Critério de aceitação
- [x] Todos os membros do time terem aprendido os comandos básicos e as funcionalidades do Git/Github

**Comment by Julio-eng** [comment]
Materiais para estudo:
1. https://www.youtube.com/watch?v=UBAX-13g8OM&t=2010s
2. https://www.youtube.com/watch?v=8JJ101D3knE&t=1026s
3. https://appointment-octopus.github.io/ebook/1_Introdu%C3%A7%C3%A3o/3_Git/index.html

**Comment by Alladin-51** [comment]
Aprendi as funcionalidades básicas do git/github.

**Comment by charles-serafim** [comment]
Obrigado pelo material, Julio! Ajudou bastante.
