### ISSUE TITLE
Estudo de Node + Express

### ISSUE THREAD

**Issue by MateusCaltabiano** [fga-eps-mds/Tema03-timeb#20]
### Descrição
Estudo fundamental para iniciar o desenvolvimento do projeto

### Tarefas

- [x] Se familiarizar com o Node
- [x] Se familiarizar com o Express
- [x] Buscar como poderá ser implementado no projeto
### Critérios de aceitação
- [x] Compartilhar as informações encontradas (sites/vídeos/resumos)
- [x] Reunião com membros dos times para compartilhar o andamento do estudo

**Comment by iagocabral** [comment]
https://www.youtube.com/watch?v=LLqq6FemMNQ&list=PLJ_KhUnlXUPtbtLwaxxUxHqvcNQndmI4B&index=1Curso interessante de Node.js no youtube:

**Comment by MatheusHenrickSantos** [comment]
O site a seguir é uma introdução a programação web utilizando Node/Express e banco de dados. Usando um exemplo de código, bem simples, ele ensina a carregar um programa em um endereço na web.
https://developer.mozilla.org/pt-BR/docs/Learn/Server-side/Express_Nodejs/Introduction
