### ISSUE TITLE
Estudo de MongoDB

### ISSUE THREAD

**Issue by MateusCaltabiano** [fga-eps-mds/Tema03-timeb#21]
### Descrição
Estudo fundamental para iniciar o desenvolvimento do projeto
### Tarefas

- [x] Se familiarizar com o banco de dados MongoDB
- [x] Buscar como poderá ser implementado no projeto
### Critérios de aceitação

- [x] Compartilhar as informações encontradas (sites/vídeos/resumos)
- [x]  Reunião com membros dos times para compartilhar o andamento do estudo

**Comment by phnog** [comment]
[Site do MongoDB](https://www.mongodb.com/cloud/atlas/lp/try2?utm_content=controlhterms&utm_source=google&utm_campaign=gs_americas_brazil_search_core_brand_atlas_desktop&utm_term=mongo&utm_medium=cpc_paid_search&utm_ad=e&utm_ad_campaign_id=12212624308&adgroup=115749706023&gclid=CjwKCAiAo4OQBhBBEiwA5KWu_1NU3_jPUxALrK20zp8ooriWc-j7gka_6EzVUPkiMuJr-ZRBmDGHIBoCwM0QAvD_BwE)

[Facilidades do MongoDB](https://www.tecmundo.com.br/mercado/137799-facilidades-banco-dados-mongodb.htm)
