### ISSUE TITLE
Criar Documento de Visão

### ISSUE THREAD

**Issue by phnog** [fga-eps-mds/Tema03-timeb#4]
# Descrição
Criar um markdown com as estruturas de um documento de visão. 
# Tarefas
- [x] Introdução --> Matheus Soares
- [x] Posicionamento --> Iago
- [x] Descrição da parte interessada e do usuário --> Pedro
- [x] Visão geral do produto --> Matheus Perillo
# Critérios de Aceitação
- [x] Markdown estar no repositório; 
- [x] Revisão por pares - João Victor e Mateus Caltabiano;

**Comment by CorreiaJV** [comment]
Sugiro utilizarmos como base o documento de visão do projeto Hortum: https://fga-eps-mds.github.io/2020.2-Hortum/Documento_de_visao/
