### ISSUE TITLE
Estudo do documento de visão.

### ISSUE THREAD

**Issue by phnog** [fga-eps-mds/Tema03-timeb#6]
# Descrição 
Entender qual a função e como fazer um Documento de Visão.
# Tarefas 
- [x] Pesquisar sobre a função e a estrutura de um Documento de Visão.
- [x] Procurar Documentos de Visão para usar como exemplo.
# Critérios de Aceitação
- [x] Divulgação do conhecimento adquirido com o grupo.

**Comment by iagocabral** [comment]
## Documento de Visão.

O documento de visão define o escopo de alto nível e o propósito de um programa, produto ou projeto. Uma instrução clara do problema, solução proposta e os recursos de alto nível do produto ajudam a estabelecer expectativas e a reduzir riscos. De forma simples um documento de visão tem como objetivo 
fornecer uma visão ampla do produto que se pretende desenvolver, sem se aprofundar em detalhes.

### Estrutura de um Documento de Visão.
 1. Introdução
 2. Posicionamento
 3. Descrições da Parte Interessada e do Usuário
 4. Visão Geral do Produto
 5. Recursos do Produto
 6. Restrições
 7. Requisitos Funcionais
 
### Exemplos de Documentos de Visão.
[Modelo de Documento de Visão IBM](https://www.ibm.com/docs/pt-br/elm/6.0.5?topic=requirements-vision-document)

[Documento de Visão Hortum(grupo MDS 2021-1)](https://fga-eps-mds.github.io/2020.2-Hortum/Documento_de_visao/)
